name: vero_progetto_piu
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Anton
      fonts: 
        - asset: assets/fonts/AntonRegular.ttf
          weight: 400
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSansRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
    - family: Actor
      fonts: 
        - asset: assets/fonts/ActorRegular.ttf
          weight: 400
